// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiQoLxloiaKwCo9OAP5jM_DXmP_MScjdM',
    appId: '1:47159019208:web:57facc9dece4d16b2507fd',
    messagingSenderId: '47159019208',
    projectId: 'campx-360de',
    authDomain: 'campx-360de.firebaseapp.com',
    storageBucket: 'campx-360de.firebasestorage.app',
    measurementId: 'G-J19MQWNJRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD8WvKke64J7qvYDtxcQVGoBXv5DYEqZY',
    appId: '1:47159019208:android:870f03bb4fc389712507fd',
    messagingSenderId: '47159019208',
    projectId: 'campx-360de',
    storageBucket: 'campx-360de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1EE-AsaZ5x7rJw5R59qKCdG-bejHeigM',
    appId: '1:47159019208:ios:74dd728fe33002ea2507fd',
    messagingSenderId: '47159019208',
    projectId: 'campx-360de',
    storageBucket: 'campx-360de.firebasestorage.app',
    iosBundleId: 'com.campx.campx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiQoLxloiaKwCo9OAP5jM_DXmP_MScjdM',
    appId: '1:47159019208:web:55eeac61e4ff33562507fd',
    messagingSenderId: '47159019208',
    projectId: 'campx-360de',
    authDomain: 'campx-360de.firebaseapp.com',
    storageBucket: 'campx-360de.firebasestorage.app',
    measurementId: 'G-9PF581RSJS',
  );
}
